FROM node:22-alpine

WORKDIR /app

RUN npm install -g @quasar/cli

COPY . .

RUN npm install

EXPOSE 8080

ENV QUASAR_PUBLIC_FOLDER=/app/public
ENV NODE_ENV=development 
ENV HOST=0.0.0.0
ENV PUBLIC=true

# Démarrer le serveur de développement avec les bons paramètres
CMD ["quasar", "dev", "--host", "0.0.0.0", "--port", "8080"]