services:
  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile.dev
    container_name: quizzfiesta-frontend
    ports:
      - "9000:8080"
    volumes:
      - ./Frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - HOST=0.0.0.0
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    depends_on:
      - backend
    networks:
      - quizzfiesta-network

  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile.dev
    container_name: quizzfiesta-backend
    ports:
      - "3000:3000"
    volumes:
      - ./Backend:/app
      - /app/node_modules
    env_file:
      - ./Backend/.env
    environment:
      - NODE_ENV=development
    networks:
      - quizzfiesta-network

networks:
  quizzfiesta-network:
    driver: bridge