name: CI Frontend & Backend

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install backend dependencies
        run: |
          cd Backend
          npm ci

      - name: Lint backend
        run: |
          cd Backend
          npm run lint

      - name: Check backend formatting
        run: |
          cd Backend
          npx prettier --check "**/*.{js,json,md}" --ignore-path .gitignore

      - name: Run backend tests
        run: |
          cd Backend
          npm test

      - name: Install frontend dependencies
        run: |
          cd Frontend
          npm ci || npm install --legacy-peer-deps

      - name: Lint frontend
        run: |
          cd Frontend
          npm run lint

      - name: Check frontend formatting
        run: |
          cd Frontend
          npx prettier --check "**/*.{js,vue,scss,html,md,json}" --ignore-path .gitignore

      - name: Run frontend tests
        run: |
          cd Frontend
          npm test
